### ISSUE TITLE
Handle tests with GET requests

### ISSUE THREAD

**Issue by kennethmorton** [davefol/api-watchdog#2]

**Comment by cbizon** [comment]
Is this ticket why https://github.com/ranking-agent/api-watchdog-translator-tests/blob/main/bl_lookup/bl_lookup.watchdog.json fails every day?

**Comment by maximusunc** [comment]
Yeah, looks like it. We've merged a way to GET in api-watchdog #5 , but there are a couple blockers with deploying the new version.

**Comment by cbizon** [comment]
OK.  I'd like to also add a test to make sure we have the right number of KPs registered in the registry, but that's a GET as well, so I'll wait until this is resolved.

**Comment by maximusunc** [comment]
This seems to be taken care of.
