### ISSUE TITLE
trapi.CURIE validation

### ISSUE THREAD

**Issue by kennethmorton** [davefol/api-watchdog#8]
Is broken given recent reasoner-pydantic updates. Since reasoner-pydantic CURIE type is now a subclass of str instead of the reasoner-pydantic base type validation doesn't work the same way.

Currently CURIE validation just checks for string. The easiest thing to do is to remove trapi.CURIE from the validation registry.

**Comment by kennethmorton** [comment]
See #9

**Comment by maximusunc** [comment]
This looks to be merged in and not an issue.
